### ISSUE TITLE
Module build failed: Error: Module failed because of a eslint error.

### ISSUE THREAD

**Issue by ghost** [MozaikAgency/wp-theme-bootstrap#276]
Hi - so I'm having some issues with one of my projects, all seemed well on my Mac, but I moved it onto my Windows machine, which evidently has now broke everything.

npm -v: 
3.10.10

node -v:
6.10.0

Here are some of the outputs im getting from gulp build, i'm not getting much, these are the most useful ones
`./assets/js/main.js
Module build failed: Error: Module failed because of a eslint error.`

`[22:45:20] Plumber found unhandled error:
 Error in plugin 'webpack-stream'
Message:
    ./assets/js/main.js`

`at lint (c:\dev\www\x\htdocs\wp-content\themes\blocky\node_modules\eslint-loader\index.js:131:17)
    at Object.module.exports (c:\dev\www\x\htdocs\wp-content\themes\blocky\node_modules\eslint-loader\index.js:197:3)
 @ multi main`

**Comment by peter-brennan** [comment]
have you tried deleting the node_module folder and running `npm install` ? Not sure if it will fix your issue but it's worth a try

**Comment by ghost** [comment]
@peter-brennan thanks Pete, no look there though, tried that and just get the same error! Boo!

**Comment by dnspnjrs** [comment]
@peteratkinson i have exactly the same problem but on a mac. Were you able to solve this?

node: v5.0.0
npm: v3.3.6

`Plumber found unhandled error:
 Error in plugin 'webpack-stream'`

`Module build failed: Error: Cannot read config file: ___dirname___/wp-content/themes/__themename__/.eslintrc`

Update:
Ok. What worked for me is manually adding the `.eslintrc` file to the dev_theme folder...

**Comment by dnspnjrs** [comment]
Ok. What worked for me is manually adding the `.eslintrc` file to the dev_theme folder...

**Comment by ghost** [comment]
Thanks, @dnspnjrs I'll give it a whirl and get back to you on it!

**Comment by ghost** [comment]
Ok so I've managed to resolve this - was an issue with Eslint throwing an error on unused vars, which was preventing gulp from building the JS!
