### ISSUE TITLE
Cannot find module 'dateformat' 'through2' when building

### ISSUE THREAD

**Issue by AlexGustafsson** [MozaikAgency/wp-theme-bootstrap#78]
I'm facing this error each time I try to build:

```
[19:00:08] Error: Cannot find module 'dateformat'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\usernamehere\Directory\node_modules\gulp-add\node_modules\gulp-util\lib\date.js:1:80)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

```
[19:17:01] Error: Cannot find module 'through2'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\usernamehere\Directory\node_modules\gulp-add\node_modules\gulp-util\lib\noop.js:1:77)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

This is after i've ran npm install as mentioned in the docs.

If I try to install the missing module

```
npm install dateformat
```

or

```
npm install --save dateformat
```

or

```
npm install --save-dev dateformat
```

I'm always faced with the following error:

```
 E:\usernamehere\AppData\Roaming\npm\node_modules\gulp\node_modules\semv
er\semver.js:281
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: undefined
    at new SemVer ( E:\usernamehere\AppData\Roaming\npm\node_modules\gul
p\node_modules\semver\semver.js:281:11)
    at SemVer.compare ( E:\usernamehere\AppData\Roaming\npm\node_modules
\gulp\node_modules\semver\semver.js:348:13)
    at compare ( E:\usernamehere\AppData\Roaming\npm\node_modules\gulp\n
ode_modules\semver\semver.js:571:31)
    at Function.gt ( E:\usernamehere\AppData\Roaming\npm\node_modules\gu
lp\node_modules\semver\semver.js:600:10)
    at Liftoff.handleArguments ( E:\usernamehere\AppData\Roaming\npm\nod
e_modules\gulp\bin\gulp.js:99:14)
    at Liftoff.<anonymous> ( E:\usernamehere\AppData\Roaming\npm\node_mo
dules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports ( E:\usernamehere\AppData\Roaming\npm\node_modules
\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> ( E:\usernamehere\AppData\Roaming\npm\node_mo
dules\gulp\node_modules\liftoff\index.js:185:9)
    at  E:\usernamehere\AppData\Roaming\npm\node_modules\gulp\node_modul
es\liftoff\index.js:159:9
    at E:\usernamehere\AppData\Roaming\npm\node_modules\gulp\node_modul
es\v8flags\index.js:99:14
```

What is the problem and how can I fix it?

PS.
Maybe unrelated, but everytime this error occurs, package.json is removed...

**Comment by Maximilianos** [comment]
Hey, I wonder whether this was something to do with an incomplete `npm install`

Have you tried completely blowing away your `node_modules`, running `npm install` again, making sure it completed ok without errors and then running the build task again? it looks like the issue you are facing is something to do with two of `gulp-add`s dependencies not installing correctly. You can also try looking through the gulp-add/through2/dateformat repos for this issue

hope this helps!
